apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedDeployment
  metadata:
    labels:
      name: mysql
    name: mysql
  spec:
    template:
      metadata:
        labels:
          name: mysql
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: mysql
        template:
          metadata:
            labels:
              name: mysql
          spec:
            containers:
            - image: mysql:5.7
              name: mysql
              env:
              - name: MYSQL_ALLOW_EMPTY_PASSWORD
                value: "1"
              - name: MYSQL_DATABASE
                value: "pacman"
              ports:
              - name: mysql
                containerPort: 3306
              args:
              - --external-locking
              - --delay-key-write=OFF
              volumeMounts:
                - name: mysql-db
                  mountPath: /var/lib/mysql
                - name: mysqld
                  mountPath: /etc/mysql
            volumes:
              - name: mysql-db
                persistentVolumeClaim:
                  claimName: glusterfs-mysql-pacman
              - name: mysqld
                persistentVolumeClaim:
                  claimName: mysqld
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedDeploymentPlacement
  metadata:
    name: mysql
    namespace: gfs
  spec:
    clusterNames:
    - cluster1
    - cluster2
    - cluster3
