apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedService
  metadata:
    name: mysql
  spec:
    template:
      metadata:
        labels:
          name: mysql
      spec:
        type: LoadBalancer
        ports:
          - port: 3306
            targetPort: 3306
        selector:
          name: mysql
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedServicePlacement
  metadata:
    name: mysql
    namespace: gfs
  spec:
    clusterNames:
    - cluster1
    - cluster2
    - cluster3
