apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-glusterfs-mysql
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs
    path: mysql3
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

