apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: standalone-cinder-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: standalone-cinder-provisioner
    spec:
      containers:
      - name: standalone-cinder-provisioner
#        image: "quay.io/external_storage/standalone-cinder-provisioner:latest"
        image: "quay.io/aglitke/standalone-cinder-provisioner:latest"
        imagePullPolicy: IfNotPresent
        env:
        - name: OS_AUTH_URL
          value: http://172.18.8.229:5000/v2.0 # obtained from /root/keystonerc_admin file but replace v3 with v2.0
        - name: OS_USERNAME
          value: admin
        - name: OS_PASSWORD
          value: 4241004c69d34c9f             # obtained from /root/keystonerc_admin file
        - name: OS_TENANT_ID
          value: 4965a4662eba4356851d05e64edaaf65 # obtained from command openstack project list and take id for admin project
        - name: OS_REGION_NAME
          value: RegionOne

