apiVersion: v1
kind: Pod
metadata:
  name: nfs-bb-pod4
spec:
  securityContext:
    runAsUser: 1000
    supplementalGroups: [2324]
  containers:
  - name: nfs-bb-pod4
    image: busybox
    command: ["sleep", "600000"]
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /usr/share/busybox/nfsshare
      name: nfsvol
  volumes:
  - name: nfsvol
    nfs:
      path: /nfsshare/folder1
      server: ip-172-18-9-105.ec2.internal


