apiVersion: v1
kind: Pod
metadata:
  name: photo1
  labels:
    name: photo1
spec:
  containers:
  - env:
    - name: OBJECT_STORAGE_BUCKET1
      value: "screeley-crossplane5"
    - name: BUCKET_NAME
      value: "screeley-crossplane5"
    - name: BUCKET_ID
      valueFrom:
            secretKeyRef:
              name: screeley-crossplane5
              key: username
    - name: BUCKET_PWORD
      valueFrom:
            secretKeyRef:
              name: screeley-crossplane5
              key: password
    - name: OBJECT_STORAGE_S3_TYPE
      value: "aws"
    - name: OBJECT_STORAGE_CLUSTER_PORT
      value: "443"
    - name: OBJECT_STORAGE_REGION
      value: "us-west-1"
    image: docker.io/zherman/demo:latest
    imagePullPolicy: Always
    name: photo1
    ports:
    - containerPort: 3000
      protocol: TCP

