apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedDeployment
  metadata:
    labels:
      name: nginx
    name: nginx
  spec:
    template:
      metadata:
        labels:
          name: nginx
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: nginx
        template:
          metadata:
            labels:
              name: nginx
          spec:
            containers:
            - image: nginx
              name: nginx
              ports:
              - name: nginx
                containerPort: 80
              volumeMounts:
                - name: nginx-share
                  mountPath: /usr/share/nginx/html
            securityContext:
              privileged: true
            volumes:
              - name: nginx-share
                persistentVolumeClaim:
                  claimName: nginx-storage
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedDeploymentPlacement
  metadata:
    name: nginx
    namespace: nginx
  spec:
    clusterNames:
    - cluster1
    - cluster2

