apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedService
  metadata:
    name: nginx
  spec:
    template:
      metadata:
        labels:
          name: nginx
      spec:
        type: LoadBalancer
        ports:
          - port: 80
            protocol: TCP
        selector:
          name: nginx
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedServicePlacement
  metadata:
    name: nginx
  spec:
    clusterNames:
    - cluster1
    - cluster2


