apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedService
  metadata:
    name: glusterfs
  spec:
    template:
      metadata:
        labels:
          name: glusterfs
      spec:
        type: LoadBalancer
        ports:
          - port: 24007
            name: glusterd
            targetPort: 24007
          - port: 24008
            name: management
            targetPort: 24008
          - port: 49152
            name: brick1
            targetPort: 49152
          - port: 49153
            name: brick2
            targetPort: 49153
          - port: 49154
            name: brick3
            targetPort: 49154
        selector:
          name: glusterfs
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedServicePlacement
  metadata:
    name: glusterfs
    namespace: gfs
  spec:
    clusterNames:
    - cluster1
    - cluster2
    - cluster3

