kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv-gfsdata
spec:
  volumeMode: Filesystem
  capacity:
    storage: 50Gi
  local:
    path: /usr/share/gfs/gfs-data0
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-63-33.ec2.internal


