kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-data-mongo
spec:
  volumeMode: Filesystem
  capacity:
    storage: 30Gi
  local:
    path: /data/gluster-brick1
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-63-33.ec2.internal
