apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cdi-deployment
spec:
  selector:
    matchLabels:
      app: cdi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: cdi-controller
    spec:
      containers:
      - name: cdi-controller
        image: jcoperh/cdi-controller:screeley-latest
        imagePullPolicy: Always
        env:
        - name: IMPORTER_IMAGE
          value: cdi-importer:screeley-latest


