kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv4
spec:
  capacity:
    storage: 10Gi
  local:
    path: /usr/share/cdi4
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-18-1-92.ec2.internal

