apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "golden-pvc"
  annotations:
    kubevirt.io/storage.import.endpoint: "file:///usr/share/cdi/images/tinyCore.iso"   # Required.  Format: (http||s3)://www.myUrl.com/path/of/data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

