apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongolog-gfs
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs
    path: monogolog
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

