apiVersion: v1
kind: Pod
metadata:
  name: aws-ebs-bb-pod2
spec:
  containers:
  - name: aws-ebs-bb-pod2
    image: busybox
    command: ["sleep", "600000"]
    volumeMounts:
    - mountPath: /usr/share/busybox
      name: ebsvol
  volumes:
    - name: ebsvol
      persistentVolumeClaim:
        claimName: ebs-claim
