kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: glusterfs-state
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

