apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedDeployment
  metadata:
    labels:
      name: pacman
    name: pacman
  spec:
    template:
      metadata:
        labels:
          name: pacman
      spec:
        replicas: 1
        selector:
          matchLabels:
            name: pacman
        template:
          metadata:
            labels:
              name: pacman
          spec:
            containers:
            - image: quay.io/ifont/pacman-nodejs-app:latest
              name: pacman
              ports:
              - containerPort: 8080
                name: http-server
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedDeploymentPlacement
  metadata:
    name: pacman
    namespace: gfs
  spec:
    clusterNames:
    - cluster1
    - cluster2
    - cluster3

