apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gce-claim-storageclass
 annotations:
   volume.beta.kubernetes.io/storage-class: slow
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 5Gi
