---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: glusterclusters.gluster.org
spec:
  group: gluster.org
  names:
    kind: GlusterCluster
    listKind: GlusterClusterList
    plural: glusterclusters
    singular: glustercluster
    shortNames:
    - gc
    - gluster
    categories:
    - all
  scope: Namespaced
  version: v1alpha1
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: anthill-controller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - serviceaccounts
  - secrets
  - pods
  - pods/exec
  - services
  - nodes
  - nodes/proxy
  - configmaps
  - events
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - patch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - gluster.org
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: v1
kind: Namespace
metadata:
  name: anthill
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: anthill-controller
  namespace: anthill
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: anthill-controller
  namespace: anthill
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anthill-controller
subjects:
- kind: ServiceAccount
  name: anthill-controller
  namespace: anthill
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: anthill-controller
  namespace: anthill
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anthill-controller
        anthill: controller
    spec:
      serviceAccountName: anthill-controller
      containers:
      - name: anthill
        image: jarrpa/anthill:dev
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
