apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-gce
spec:
 capacity:
   storage: 1Gi
 accessModes:
   - ReadWriteOnce
 gcePersistentDisk:
   readOnly: false
   pdName: yourdisk
   fsType: ext4
