apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "golden-pvc-centos"
  annotations:
    kubevirt.io/storage.import.endpoint: "http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2"
#    kubevirt.io/storage.import.secretName: "" # Optional.  The name of the secret containing credentials for the data source
spec:
  storageClassName: standalone-cinder
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

