kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-cinder-provisioner
  annotations:
spec:
  storageClassName: standalone-cinder
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
