apiVersion: v1
kind: Service
metadata:
  name: kubevirt
  labels:
    app: virt-handler
spec:
  ports:
  - port: 8185
    name: vhandler
  - port: 8182
    name: vlauncher
  clusterIP: None
  selector:
    app: virt-handler

