apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ceph-demo
  namespace: default
  labels:
    kubevirt.io: ""
spec:
  selector:
    matchLabels:
      name: io.kubevirt.ceph-demo
  replicas: 1
  serviceName: "ceph"
  template:
    metadata:
      labels:
        name: io.kubevirt.ceph-demo
        kubevirt.io: ""
    spec:
#      nodeSelector:
#          "kubernetes.io/hostname": "master"
      hostNetwork: true
      initContainers:
      - name: init
#        image: rmohr/cinder-ceph-demo
        image: aglitke/cinder-ceph-demo
        command: ["/bin/bash", "-c", "cp -v /data/scripts/* /scripts/ && cp /data/etc/* /etc/cinder/"]
        volumeMounts:
        - name: scripts
          mountPath: "/scripts"
        - name: cinderetc
          mountPath: "/etc/cinder"
      containers:
      - name: kraken
        command: ["/scripts/ceph-entrypoint.sh", "demo"]
        env:
        - name: CEPH_DEMO_UID
          value: "kubevirt"
        - name: CEPH_DEMO_ACCESS_KEY
          value: "kubevirt"
        - name: CEPH_DEMO_SECRET_KEY
          value: "kubevirt"
        - name: CEPH_DEMO_BUCKET
          value: "kubevirt"
        - name: MON_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CEPH_PUBLIC_NETWORK
          value: "0.0.0.0/0"
        image: ceph/demo
        volumeMounts:
        - name: scripts
          mountPath: "/scripts"
        - name: cephvarlib
          mountPath: /var/lib/ceph
        - name: cephetc
          mountPath: /etc/ceph
      - name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "cinder"
        - name: MYSQL_USER
          value: "cinder"
        - name: MYSQL_PASSWORD
          value: "password"
        image: mariadb
        volumeMounts:
        - name: mariadbdata
          mountPath: "/var/lib/mysql"
      - name: rabbitmq
        image: rabbitmq
      - name: cinder-api
        image: rmohr/cinder:ocata
        command: ["/scripts/cinder-api.sh"]
        env:
        - name: INIT_DB
          value: "true"
        volumeMounts:
        - name: scripts
          mountPath: "/scripts"
        - name: cinderetc
          mountPath: "/etc/cinder"
      - name: cinder-scheduler
        image: rmohr/cinder:ocata
        command: ["cinder-scheduler"]
        volumeMounts:
        - name: cinderetc
          mountPath: "/etc/cinder"
      - name: cinder-volume
        image: rmohr/cinder:ocata
        command: ["/scripts/ceph-service.sh"]
        env:
        - name: MON_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: scripts
          mountPath: "/scripts"
        - name: cinderetc
          mountPath: "/etc/cinder"
        - name: cephetc
          mountPath: "/etc/ceph"
      - name: cinder-provisioner
        image: quay.io/aglitke/standalone-cinder-provisioner:latest
        env:
        - name: OS_CINDER_ENDPOINT
          value: http://127.0.0.1:8776/v3
#          value: http://127.0.0.1:8776/v2.0
      volumes:
      - name: scripts
        emptyDir: {}
#      - name: scripts
#        hostPath:
#          path: "/etc/demo/scripts"
      - name: cinderetc
        emptyDir: {}
      - name: cephvarlib
        emptyDir: {}
      - name: cephetc
        emptyDir: {}
#      - name: cephetc
#        hostPath:
#          path: "/etc/ceph"
      - name: mariadbdata
        emptyDir: {}
#  volumeClaimTemplates:
#  - metadata:
#      name: cephetc
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: demo
#      resources:
#        requests:
#          storage: 20Gi
#  - metadata:
#      name: cephvarlib
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: demo
#      resources:
#        requests:
#          storage: 20Gi
#  - metadata:
#      name: cinderetc
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: demo
#      resources:
#        requests:
#          storage: 20Gi
#  - metadata:
#      name: mariadbdata
#    spec:
#      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: demo
#      resources:
#        requests:
#          storage: 80Gi

---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: standalone-cinder
provisioner: openstack.org/standalone-cinder
---
apiVersion: v1
kind: Secret
metadata:
  name: standalone-cinder-cephx-secret
type: "kubernetes.io/rbd"
data:
  key: QVFDMkI0SmE2MDgzT3hBQTdOR0dpb0xpR1lqOHlJTFpkYUI1T0E9PQo=

