apiVersion: v1
kind: List
items:
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedService
  metadata:
    name: photo1
  spec:
    template:
      metadata:
        labels:
          name: photo1
      spec:
        type: LoadBalancer
        ports:
          - port: 3000
            targetPort: 3000
        selector:
          name: photo1
- apiVersion: core.federation.k8s.io/v1alpha1
  kind: FederatedServicePlacement
  metadata:
    name: photo1
  spec:
    clusterNames:
    - cluster1
    - cluster2
    - cluster3
