apiVersion: v1
kind: PersistentVolume
metadata:
  name: photogallery1-gfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs
    path: photogallery1
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

